### ISSUE TITLE
CoreMIDI backend

### ISSUE THREAD

**Issue by Boddlnagg** [Boddlnagg/midir#1]
See https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L379-L1073 for reference.

I can't implement this myself since I don't own an OS X device.

**Comment by ConnorGray** [comment]
Hey, I'm interested in there being a CoreMIDI backend. I've not done this kind of programming before, but I'd be willing to give it a shot. Any tips?

**Comment by Boddlnagg** [comment]
@ConnorGray Great! I'm going to try to help you and mentor you as much as I can. However, this is probably going to be quite hard if you don't have experience with either (1) the OS X APIs and/or (2) unsafe Rust programming. Still, I don't want to discourage you.

The first step would be to have some low-level bindings to CoreMIDI. I'm not sure if there are some already, but there are (low level and high level) bindings to Core Foundation at https://github.com/servo/core-foundation-rs. If you don't find any CoreMIDI bindings, you would have to generate them using [rust-bindgen](https://github.com/Yamakaky/rust-bindgen) from the C header files.

Then, you could either try to wrap the CoreMIDI lowlevel API in a safe high-level API (independent from midir, but providing all the necessary functionality), or write a more or less direct port of https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L379-L1073, while using as much as possible from the safe APIs in https://crates.io/crates/core-foundation (which you should include as a dependency).

However, I have refactored the API a bit from the original RtMidi code, so you have to find out which of the original functions matches the ones existing now. One part that especially changed quite a bit is error handling.

I would recommend porting the different parts in the following order (starting from the easiest part):
- Enumerating MIDI output ports (this should really be a good introduction)
- Implementing MIDI output
- Enumerating MIDI input ports
- Implementing MIDI input (this is probably the hardest part because it requires a callback function, similar to what's happening in the `winmm` Windows backend)
- Virtual ports (not really hard after the rest is done)

In general, the Windows `winmm` backend is probably the most similar to CoreMIDI, so you can try to get some inspiration from there.

I hope that this helps to get you started! 👍

**Comment by Boddlnagg** [comment]
Oh, and if you haven't done any unsafe Rust programming before, I'd recommend the [Rustonomicon](https://doc.rust-lang.org/nightly/nomicon/)

**Comment by ConnorGray** [comment]
@Boddlnagg Wow, great! Thanks for the detailed breakdown, I was totally lost before. I've done a decent amount of Swift/C++ programming in the past, so hopefully it's not too foreign.

**Comment by ConnorGray** [comment]
@Boddlnagg Yes, that definitely seems useful, thanks!

**Comment by ConnorGray** [comment]
Some quick Google shows that there's an existing set of Rust CoreMIDI bindings/wrapper in [core-midi](https://crates.io/crates/core-midi/) and [core-midi-sys](https://crates.io/crates/core-midi-sys), so 

- [X] CoreMIDI Wrapper

**Comment by Boddlnagg** [comment]
Great! This didn't exist yet when I looked for it last time.

And one more thing: The whole platform-specific API surface is wrapped in https://github.com/Boddlnagg/midir/blob/master/src/common.rs (mainly to have a centralized place for documentation, which does not yet exist), using the re-exports defined in https://github.com/Boddlnagg/midir/blob/master/src/backend/mod.rs. The actual implementation should be in a folder `backend/coremidi/`

**Comment by jonas-k** [comment]
I have worked a bit on bringing midir to macOS, too. I've created a Gist with my current state. It throws compiler errors, so it is not ready for integration into midir, but it might be a good starting point for someone trying to implement the coreMIDI module.
https://gist.github.com/anonymous/fe58d169f626a5f0031bb7080f516f6e

**Comment by chris-zen** [comment]
As of today, there are 2 low-level bindings for CoreMIDI:
- [core-midi-sys](https://crates.io/crates/core-midi-sys) which is incomplete
- [coremidi-sys](https://github.com/jonas-k/coremidi-sys) which I haven't tested but looks complete.

@jonas-k, @dtwood have you considered joining efforts ?

@ConnorGray any progress on your contribution to midir ? I might be interested in contribute too. After looking at the code for RtMidi.cpp suggested by @Boddlnagg the effort for having OSX integrated in midir looks reasonable if coremidi-sys from jonas-k works as expected and he is open to eventual suggestions and to publish it into cargo.

**Comment by chris-zen** [comment]
FYI I started to work on this, but I decided to start first by creating a rust library for CoreMIDI on top of [coremidi-sys](coremidi-sys). Once it is working, adding support in midir for CoreMIDI will be quite easy. You will find more details at https://github.com/chris-zen/coremidi

**Comment by Boddlnagg** [comment]
Is anyone actively working on this? I'm going to have a look again at the current state of https://github.com/chris-zen/coremidi (@chris-zen) and will try to integrate it into midir.

**Comment by chris-zen** [comment]
@Boddlnagg That was my initial motivation for writing the coremidi binding, but at the end I run of time credit to do so. So I am very happy to see someone looking at that :-)
Not that I have much free time now, but I'll try to help as much as I can ;-)

**Comment by Boddlnagg** [comment]
@chris-zen I have sent a few PRs, maybe you can have a look at them? I'm currently waiting for them to be merged before I can finish the CoreMIDI backend in midir and release a new version.
