### ISSUE TITLE
Multiple input ports 

### ISSUE THREAD

**Issue by elmcapp** [Boddlnagg/midir#105]
On MacOS it would be nice if we can have multiple input ports. In my old app I was able to do this and would hate to lose this feature as I moved from Electron to Tauri. 

Are we able to setup multiple input ports. I need to be able to listen to multiple or all midi device at once (input ports)? 

If not, are we able to create multiple instances. If so could you please provide an example how.

**Comment by Boddlnagg** [comment]
Unfortunately this can't be implemented in a cross-platform way, please see the explanation in #67.

You can use a macOS library directly (i.e. https://github.com/chris-zen/coremidi) to get this to work on macOS.

**Comment by elmcapp** [comment]
For example lets say that I have 4 midi controllers connected to the same MacBook Pro computer. I want to read the input for each of the devices simultaneously. In order to do so I have to create 4 of the same functions with the only difference being the port number to read. When doing so I am able to read the input of all 4 midi devices. Of course I am not 100% sure if that can be done in rust along but to achieve this I also put midir in the app state which created 4 different instances.

Is there a way that you could create an update to allow this without creating 4 different functions. At lease allow the platforms that could support this work. So many use cases that A user would want to read all inputs from all connected midi controllers
