### ISSUE TITLE
bug: future-incompatibility warning with midir 0.7.0

### ISSUE THREAD

**Issue by insomnimus** [Boddlnagg/midir#107]
With the latest cargo nightly as of today (2022/04/24), compiling any app that depends on `midir` displays a rather serious warning message.

the output is too large so i'm putting a link to it instead: <https://termbin.com/2jvy>

The same report can be generated by using the command below:\
`cargo report future-incompatibilities --id 7 --package midir:0.7.0`

I'm putting the first warning message here for convenience (there are more).

```output
   [...]     
The package `midir v0.7.0` currently triggers the following future incompatibility lints:
> warning: reference to packed field is unaligned
>    --> D:\home\.cargo\registry\src\github.com-1ecc6299db9ec823\midir-0.7.0\src\backend\winmm\mod.rs:100:38
>     |
> 100 |         let pname: &[u16] = unsafe { &device_caps.szPname }; // requires unsafe because of packed alignment ...
>     |                                      ^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: `#[allow(unaligned_references)]` on by default
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #82523 <https://github.com/rust-lang/rust/issues/82523>
>     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
>     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)
[...]
```

**Comment by Boddlnagg** [comment]
Will be fixed in 0.8.0 through f6d7a8e05bb7fea5e21e25b5449dd2acbec973c3

I might also do a 0.7.1 release to allow 0.7 to be built with the most recent rustc.

**Comment by Boddlnagg** [comment]
Will the solution in #108 be sufficient for you?

**Comment by insomnimus** [comment]
I can't test that branch right now but as long as cargo emits none of these warnings I think that solves the issue.

**Comment by insomnimus** [comment]
I could wait for the next release so it's fine as is right now, just wanted to give a heads-up.

**Comment by Boddlnagg** [comment]
With the release of 0.8.0 I'm closing this issue.
