### ISSUE TITLE
Undefined behaviour in the ALSA backend

### ISSUE THREAD

**Issue by PatchMixolydic** [Boddlnagg/midir#110]
In `midir::backend::alsa::handle_input`, the code that creates `poll_fds` contains undefined behaviour:

https://github.com/Boddlnagg/midir/blob/1656fbd7b38b7b20a19eb0f0704ebb1459599d61/src/backend/alsa/mod.rs#L600-L610

Specifically, the call to `Vec::set_len` immediately after `Vec::with_capacity` exposes uninitialized `libc::pollfd`s. Per [`Vec::set_len`'s safety contract](https://doc.rust-lang.org/std/vec/struct.Vec.html#safety-2), this is not allowed.

**Comment by Boddlnagg** [comment]
This implementation predates the existence of `MaybeUninit`, which would probably be the best solution here.
However, the functionality from the alsa library that's used here (https://docs.rs/alsa/latest/alsa/poll/trait.Descriptors.html#tymethod.fill) itself won't probably work in combination with `MaybeUninit`, so it might be easiest to just default-initialize the whole Vec/slice.

Would you mind creating a PR?

**Comment by PatchMixolydic** [comment]
I've gone ahead and opened #113, which should hopefully fix this issue.
