### ISSUE TITLE
Example test_forward opens a connection to all ports

### ISSUE THREAD

**Issue by worikgh** [Boddlnagg/midir#111]
The example `test_forward` is making a connection to all available MIDI ports for output.  Not just the port selected by the user.

Platform: Raspberry Pi 4
```
rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

**Comment by Boddlnagg** [comment]
Is anyone else able to reproduce this?

**Comment by worikgh** [comment]
I have found the problem, I think.

It was not `midir` but a programme supplied by the makers of the Pisound card I am using

My apologies for blaming `midir`.
