### ISSUE TITLE
Question: Send-able events?

### ISSUE THREAD

**Issue by PetrGlad** [Boddlnagg/midir#128]
I would like to parse an SMF file and then send some events to other threads for processing. The problem is that events are bound to the file data. There is a enum that would suffice in my case, see `enum MidiMessage` in `event.rs`. But that  one has serializer functions (I need a byte representation out of it eventually) are only accessible within the crate (`pub(crate)`). Saving some space with references to source date seems to be a nice-to-have, but complicates memory management. I would like to avoid things like `ouroboros` unless absolutely necessary as I am not yet comfortable with Rust. And Arena does not seem to help as I would need to send arena with the event, returning to original problem of sending self-references.
Is there a way to make the events `Send`-able? Or did I miss something that would help with it?

**Comment by Boddlnagg** [comment]
Which `event.rs` are you referring to? `midir` always uses `&[u8]` for messages (and that reference can refer to some OS buffer, so we can't and won't change that). You can always allocate this into a `Vec<u8>` which is then `Send`able.
Just note that SysEx messages can become rather long, i.e. would allocate quite some space.

**Comment by PetrGlad** [comment]
If I send Vec<u8>  then I would have to do parsing in the receiving thread? 
Sending backing data and parsed evens together is tricky and as I was told not possible in safe rust.

**Comment by PetrGlad** [comment]
Sorry the MidiMessage I mentioned was from another crate, my mistake.

**Comment by Boddlnagg** [comment]
Okay, then I assume this issue can be closed?

**Comment by PetrGlad** [comment]
Please have a look at the question above.

**Comment by Boddlnagg** [comment]
> If I send Vec then I would have to do parsing in the receiving thread?

`midir` does not provide any functionality for event parsing anyway. So yes, you send the bytes as a `Vec<u8>` and then do any parsing or further computation in the receiving thread.

However, reading your original post again, I'm not sure if `midir` is what you want at all: `midir` is for *real-time* processing of MIDI, i.e. receiving and sending MIDI messages from/to other applications and devices. `midir` itself won't help you to parse SMF files.
