### ISSUE TITLE
resolve mingw-related build issues by updating `windows` crate

### ISSUE THREAD

**Issue by j-n-f** [Boddlnagg/midir#152]
While working on https://github.com/Boddlnagg/midir/pull/151, it was necessary to upgrade the version of the `windows` crate to resolve mingw-related issues. Unfortunately this causes problems in winrt builds:

```
error[E0277]: the trait bound `IClosable: From<windows::Devices::Midi::MidiInPort>` is not satisfied
   --> src\backend\winrt\mod.rs:164:47
    |
164 |         let closable: IClosable = self.port.0.try_into().unwrap();
    |                                               ^^^^^^^^ the trait `From<windows::Devices::Midi::MidiInPort>` is not implemented for `IClosable`, which is required by `windows::Devices::Midi::MidiInPort: TryInto<_>`
    |
    = note: required for `windows::Devices::Midi::MidiInPort` to implement `Into<IClosable>`
    = note: required for `IClosable` to implement `TryFrom<windows::Devices::Midi::MidiInPort>`
    = note: required for `windows::Devices::Midi::MidiInPort` to implement `TryInto<IClosable>`

error[E0277]: the trait bound `IClosable: From<windows::Devices::Midi::IMidiOutPort>` is not satisfied
   --> src\backend\winrt\mod.rs:266:45
    |
266 |         let closable: IClosable = self.port.try_into().unwrap();
    |                                             ^^^^^^^^ the trait `From<windows::Devices::Midi::IMidiOutPort>` is not implemented for `IClosable`, which is required by `windows::Devices::Midi::IMidiOutPort: TryInto<_>`
    |
    = note: required for `windows::Devices::Midi::IMidiOutPort` to implement `Into<IClosable>`
    = note: required for `IClosable` to implement `TryFrom<windows::Devices::Midi::IMidiOutPort>`
    = note: required for `windows::Devices::Midi::IMidiOutPort` to implement `TryInto<IClosable>`
```

It's not clear why this is happening, but this work seems separate from solving the re-entrant locking issue in #150 .

**Comment by j-n-f** [comment]
@Boddlnagg do you know why this is happening only for winrt? Just based on the types involved, I'm guessing

1. `midir` needs an update to `Cargo.toml` so that the right features are added for the `winrt` feature, _or_
2. this is an issue that needs to be resolved in the `windows` crate

**Comment by j-n-f** [comment]
All right, this was simpler than I thought. We no longer need to turn the midi ports into IClosable to close. The `windows` crate has wrapped everything up so we can just call `.Close()` on the midi ports themselves.

**Comment by Boddlnagg** [comment]
In what way does this relate to the build failures (timeouts) in https://github.com/Boddlnagg/midir/pull/146 ? (The `.close()` calls have been adjusted there already.)
