### ISSUE TITLE
test_read_input.rs panics in certain scenario

### ISSUE THREAD

**Issue by oilcake** [Boddlnagg/midir#154]
Panics on receiving note-off in exactly the same time with note-on. 

Full text of error:
`thread '<unnamed>' panicked at /Users/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/coremidi-0.8.0/src/packets.rs:91:35:
misaligned pointer dereference: address must be a multiple of 0x4 but is 0x7000025a0f41`

Setup to reproduce the issue - midir will crash exactly when E4 turns to D4:
![Screenshot 2024-05-09 at 12 42 12](https://github.com/Boddlnagg/midir/assets/66210143/777cc2ca-767f-4212-8413-28004d3bfbb5)

I am on macos Catalina(10.15.7), rustc 1.74.0, midir 0.10.0

**Comment by Boddlnagg** [comment]
This is the same issue as https://github.com/chris-zen/coremidi/issues/49 (the backtrace location in the coremidi-0.8.0 example there is also `packets.rs:91:35`).
So this is a bug in the coremidi crate.

**Comment by oilcake** [comment]
Thank you for response, at least it can be hacked, so there's hope 😀

**Comment by Boddlnagg** [comment]
On the other hand, the `Packet` based APIs have been deprecated in CoreMIDI in favor of the `Event` based APIs, so maybe `midir` should migrate ...

**Comment by Boddlnagg** [comment]
I opened a PR for coremidi-sys (https://github.com/jonas-k/coremidi-sys/pull/18).

**Comment by Boddlnagg** [comment]
This has been confirmed as fixed.
