### ISSUE TITLE
Windows: wrong port names when (external) virtual ports change

### ISSUE THREAD

**Issue by sternmull1** [Boddlnagg/midir#155]
Previouly existing ports don't disappear, and their names remain instead of new ports. This happens for me on Windows and with virtual ports via loopMIDI, but not with hardware ports.

steps to reproduce:

1.) midir: list input or output ports
Let's say the ports are:
1   Microsoft GS Wavetable Synth
2   loopMIDI Port
3   loopMIDI Port 1

2.) loopMIDI: remove "loopMIDI Port 1"

3.) midir: list ports again, the list remains the same, even though number 3 doesn't exist anymore.

4.) loopMIdi: add new ports "test port 1" and "test port 2"

5.) midir: list ports again, the list now looks like this:
1   Microsoft GS Wavetable Synth
2   loopMIDI Port
3   loopMIDI Port 1
4   test port 2

when accessing number 3 (loopMIDI Port 1), it is actually "test port 1", so I guess just the old names remain in place.

(PS: This is my first time on github, in case I'm doing this issue report wrong, please let me know.)

**Comment by Boddlnagg** [comment]
You did the issue report correctly, thanks :-)

However, I'm not sure whether this is an issue in midir, in the Windows MIDI infrastructure, or in loopMIDI.
I assume you're using the default backend, not the `winrt` backend? Can you retry with the `winrt` backend (by enabling the `winrt` Cargo feature)?

Also, do you have any other software that also enumerates MIDI parts, with which you could cross-check that loopMIDI is not at fault?

**Comment by sternmull1** [comment]
Thanks for the quick reply! I just tested the same with two programs that can list MIDI ports (should have tried that before) and noticed the same behavior, so it seems this isn't a midir issue at all. Sorry for the confusion. Ableton shows the wrong names, but ones that don't exist anymore turn red.
Something I don't understand is that when I restart my program, the names are correct, but when I create a new MidiInput instance within the program, the wrong names remains the same.

On that note, is there any chance for virtual ports in midir on Windows anytime soon?
