### ISSUE TITLE
Multiple ports?

### ISSUE THREAD

**Issue by jswrenn** [Boddlnagg/midir#39]
Does this library provide a mechanism for creating a multiple ports associated with a single client?

**Comment by Boddlnagg** [comment]
This is currently not supported. It would require an API change and the concept of "client" does not exist on most backends, so I'm not sure whether I want to support it. Could you explain your specific usecase, and what would be the problem with creating multiple clients?

**Comment by jswrenn** [comment]
I'm currently using midir in two projects:
 - [_bam_](https://github.com/jswrenn/bam) plays MIDI events using the PC motherboard speaker.
 - [_midiplex_](https://github.com/jswrenn/midiplex) consumes a potentially polyphonic MIDI even stream and produces _N_ monophonic output streams.

I'm using these two utilities to orchestrate a lab of ~80 computers. Each computer is running _bam_ and _aseqnet_ in server mode. Then, on my laptop, I'm running 80 instances of _aseqnet_ in client mode, and _midiplex_ with 80 output streams.

All told, this currently entails creating something like 161 MIDI devices: each instance of _aseqnet_ corresponds to an input device; _midiplex_ creates one input device and 80 output devices. However, ALSA takes issue with creating more than 64 devices:
```
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Cannot allocate memory
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitError', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I've done a bit of testing and it appears that there's no such limit on the number of ports a client can have. Currently, it looks like the only way I'll be able to orchestrate all 80 computers with _midiplex_ and _aseqnet_ is to rewrite the two utilities to create devices that have many ports, instead of creating many devices that have one port. (Alternatively, I could try to figure out where this limit is encoded and raise it.)

**Comment by Boddlnagg** [comment]
This sounds like an interesting project! However, if you only need the ALSA backend, it might be a good idea to just use [alsa-rs](https://github.com/diwic/alsa-rs) directly (you can basically copy the ALSA backend code from midir). I might change midir's API in the future to enable things like what you want, but it won't be soon, because I don't have much time at the moment.

**Comment by Boscop** [comment]
Can't you just split the stream into 40 streams twice, on 2 different cascaded computers?

**Comment by jswrenn** [comment]
Even two conducting computers would be insufficient, @Boscop. Using _aseqnet_ and _midiplex_ (before I rewrote it), for each performing computing, there will be two MIDI devices created on the conducting computer (a _midiplex_ source and an _aseqnet_ sink). Therefore, in a one-port-per-client model, each conducting computer can only control about thirty performing computers; we would need _three_ conducting computers to utilize the entire lab.

However, any multi-layered approach isn't ideal. It makes it more difficult to reason about note allocations, and more difficult to rein in latency issues.

At any rate, I've already [rewritten _midiplex_](https://github.com/jswrenn/midiplex/commit/ac865e2b64534553528822a506243829cf196af1) and am working on a similar [reimplementation of _aseqnet_](https://github.com/jswrenn/midinet). The only regression is that I don't have quite enough Linux experience to know how to work with ALSA/Linux's polling APIs (e.g., [this](https://github.com/Boddlnagg/midir/blob/5e90714e5bd5eb9062c19ca1d934dfec767d9711/src/backend/alsa/mod.rs#L574-L586) is all a little mystifying to me) so they burn CPU time.

**Comment by Boddlnagg** [comment]
> The only regression is that I don't have quite enough Linux experience to know how to work with ALSA/Linux's polling APIs (e.g., this is all a little mystifying to me) so they burn CPU time.

The snippet you pointed to is basically extracting the poll descriptor from ALSA and adding another file descriptor (at index 0) which refers to a pipe created in https://github.com/Boddlnagg/midir/blob/5e90714e5bd5eb9062c19ca1d934dfec767d9711/src/backend/alsa/mod.rs#L183-L191. [This line](https://github.com/Boddlnagg/midir/blob/5e90714e5bd5eb9062c19ca1d934dfec767d9711/src/backend/alsa/mod.rs#L366) finally writes a value to the pipe, signaling the event handler thread that it should close itself. That way a single `poll` call in the loop inside the handler thread is sufficient to catch all MIDI events and the "close" event.

**Comment by jswrenn** [comment]
I appreciate the guidance! This seems to work nicely: https://github.com/jswrenn/midinet/blob/f29b1b826ab8070fc0116200fbe293792a0cb1c2/src/bin/client.rs#L59-L73

**Comment by Boddlnagg** [comment]
Happy to see that it worked! I'm going to close this as wontfix ... at least for the forseeable future. I want to keep the API simple and functionality that is not available cross-platform doesn't really fit in ...
