### ISSUE TITLE
Move `os::unix` module to `virtual`

### ISSUE THREAD

**Issue by Boddlnagg** [Boddlnagg/midir#41]
Currently the platforms that support virtual ports are exactly the Unix platforms, but there is no reason that this must be the case, so the module name should reflect that.

**Comment by Boscop** [comment]
Btw, it's possible on Windows through thirdparty drivers, e.g.:
https://www.tobias-erichsen.de/software/virtualmidi.html
https://www.tobias-erichsen.de/software/virtualmidi/virtualmidi-sdk.html
But I usually just create the virtual ports manually with loopMIDI:
https://www.tobias-erichsen.de/software/loopmidi.html
and then use them like normal output ports with midir.

**Comment by Boddlnagg** [comment]
Yes, but midir as a library cannot install third party drivers. That would be the responsibility of an application that uses midir

**Comment by Boscop** [comment]
I know, I'm just saying this is one way to do it..

**Comment by Boddlnagg** [comment]
I just realized that `virtual` is a reserved keyword in Rust and therefore the module can't be named that way ... not sure how best to proceed.

**Comment by faern** [comment]
I personally feel that it's much safer to name a module that is conditioned on platform after that platform. If someone imports `midir::virtual::FooBar` they might have no idea their software will not even compile on all platforms any longer.

**Comment by Boddlnagg** [comment]
I agree now. The original idea behind this proposed change was that the notion of "virtual ports" is not specifically tied to the Unix platform in theory ... but in practice it's exactly the Unix platforms that implement virtual ports. 

I'll close this issue.
