### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Boddlnagg** [Boddlnagg/midir#5]
Document all the things. Then add `#![deny(missing_docs)]`.

Maybe there is a way that we don't have to add reduntant documentation for all backends, since the interface (including documentation) should be the same on all platforms.

**Comment by Boddlnagg** [comment]
The docs should also be published online somewhere.

**Comment by 0tt** [comment]
Yes please.

**Comment by Boddlnagg** [comment]
Until the documentation is done, you can have a look at the [examples](https://github.com/Boddlnagg/midir/tree/master/examples). midir's API surface is really not very large and the examples basically cover everything.

**Comment by Boddlnagg** [comment]
This is now mostyl fixed in version 0.3.2, see https://docs.rs/midir/0.3.2/midir/

I'm leaving this open, because I've not done anything towards `#![deny(missing_docs)]`.

**Comment by Boddlnagg** [comment]
Feel free to tell me if any part of the documentation is not clear enough!
