### ISSUE TITLE
No runtime check for virtual port support

### ISSUE THREAD

**Issue by sm-Fifteen** [Boddlnagg/midir#52]
As far as the documentation and code seem to indicate, there isn't a way to verify whether on not virtual ports are supported by the MIDI backend. This is a problem for cross-platform applications, where one could for instance attempt to create a virtual port with a manual port selection fallback if that feature is not supported.

For instance:

```rust
use std::io::{stdin, stdout, Write};
use std::error::Error;

use midir::{MidiInput, MidiInputConnection, Ignore};
use midir::os::unix::VirtualInput;

fn initialize_midi_virtual() -> Result<MidiInputConnection<()>, Box<Error>> {
    let mut midi_in = MidiInput::new("midir forwarding input")?;
    midi_in.ignore(Ignore::None);

    Ok(midi_in.create_virtual("midir-forward", midi_callback, ())?)
}

fn initialize_midi_manual() -> Result<MidiInputConnection<()>, Box<Error>> {
    let mut input = String::new();

    let mut midi_in = MidiInput::new("midir forwarding input")?;
    midi_in.ignore(Ignore::None);

    println!("Available input ports:");
    for i in 0..midi_in.port_count() {
        println!("{}: {}", i, midi_in.port_name(i)?);
    }
    print!("Please select input port: ");
    stdout().flush()?;
    stdin().read_line(&mut input)?;
    let in_port: usize = input.trim().parse()?;

    println!("\nOpening connection");
    let in_port_name = midi_in.port_name(in_port)?;

    Ok(midi_in.connect(in_port, "midir-forward", midi_callback, ())?)
}
```

Given the two functions above, only the second one is valid when cross-compiling for Windows, so the first would have to be disabled based on a feature-flag like `#[cfg(not(target_os="windows"))]` and a compile-time macro check like `cfg!(not(target_os = "windows"))`. Besides requiring updates to that code should virtual ports end up being supported on Windows for whatever reason, it seems a lot more complex (it's certainly not straightforward for the user, you just have to know about these switches) than simply having some kind of `midir::supports_virtual()` function or to simply have `create_virtual` systematically fail at runtime if the backend does not support it.

Is there any reason why those features are blocked at compile-time or could that be changed into a runtime check?

**Comment by sm-Fifteen** [comment]
I just realized why it wouldn't make sense to do so, at least in the use case I was thinking about. Applications can attach to existing MIDI ports as exposed by the MIDI sound system, but an application can't connect to another application directly unless one of them has a virtual MIDI port to connect to. You can't really "fallback" from being able to create a virtual MIDI port by connecting to an existing one, since the point of virtual ports is that other applications can connect to them. In pretty much all cases, if you can't create a virtual port, then there's likely no other option.

That leaves a pretty narrow range of applications where the inability to have virtual MIDI ports doesn't affect the main functionality, but where one would also still needs to connect to existing ports.

**Comment by Boddlnagg** [comment]
Yep, I think you correctly summarized the situation in your second post. There is usually no good way to provide a runtime alternative to virtual ports. So either your application requires virtual ports (then you can only build/run on platforms that support them) or it doesn't (then it can run on all platforms).

**Comment by sm-Fifteen** [comment]
Ok, thank you for confirming. That should probably be mentionned somewhere in the doc for people who aren't super familiar with MIDI, but it at least answers my question.
