### ISSUE TITLE
Possibility to return MidiOutputPort from a function

### ISSUE THREAD

**Issue by Aries85** [Boddlnagg/midir#57]
Hello,
    recently, I have been trying to use midir library. I especially like the portability of it!

However, I ran into issue where it is not possible to return `MidiOutputPort` from a function, which would be comfortable.

Gist with demonstration (it is just refactored `test_forward.rs`): https://gist.github.com/Aries85/253b6a9f4d4f93162928e1f93cb04cdc

Maybe a clonability of `MidiOutputPort` (and possibly of `MidiInputPort`) could solve it?

Additionally, I'd like to ask following questions (maybe some of the could be put to separate issues):

- Would it be possible to add trait which would define a trait with `ports()` function on both `MidiInput` and `MidiOutput` structs? Adding this would allow to use the same code for selecting input and output midi ports.
- Would it be possible to add synchronous blocking API for handling of MIDI messages?
- Why does `MidiOutputConnection.send()` use parameter `&mut self`? Would it be possible to resolve it with _interior mutability_ ? The client code does not really do anything to mutate the variable where `MidiOutputConnection` is stored.

**Comment by Boddlnagg** [comment]
Thanks for opening this issue and pointing out the impossibility to return `MidiOutputPort`. I have fixed this in https://github.com/Boddlnagg/midir/commit/a12b3105f85731eb8367d2e2c326d1f9da11a840 now.

I have also adressed the first of your three other points in https://github.com/Boddlnagg/midir/commit/32078b793c7fdb4313f48d947ec077865da0b27c: There's now a trait `MidiIO` that is implemented by `MidiInput` and `MidiOutput` and provides a `ports()` function among others.

I'm going to prepare a release soon, when you agree that I have actually implemented what you wanted :-)

Regarding a synchronous blocking API: There is no single best approach to do this. I think you mean some kind of queueing of messages that you can then handle in a separate thread in a blocking way? You should try using a [channel](https://doc.rust-lang.org/std/sync/mpsc/fn.channel.html). If you have a specific suggestion how to improve the situation, open a new issue (or even a PR!).

Regarding `MidiOutputConnection::send()` taking `&mut self`: The mutability (which is required by most backends) probably could be hidden with interior mutability. But what benefit would that have? Feel free to open a new issue about this with some more context/explanation.

**Comment by Aries85** [comment]
The cloneability and `MidiIO` trait are great! Just did a test and it works as expected.

For the synchronous API, I was thinking about channels. Will try it.

Regarding the `MidiOutputConnection::send()` - it does not block anything, feel free to release without it. I'll look into this deeper and create separate issue with better description.

Thank you very much for your work!
