### ISSUE TITLE
Update alsa dependency to 0.4.2

### ISSUE THREAD

**Issue by Psykopear** [Boddlnagg/midir#62]
Hi,

I'm trying to use `midir` together with `RustAudio/cpal` on linux with alsa backend, but adding both as dependencies to a project, compilation fails because they link to different versions of a native library (alsa).

To reproduce the problem, just create a new project on linux, add `midir` and `cpal` as dependencies and try to run:

```
cargo new test-midir-cpal
cd test-midir-cpal
echo 'cpal = "*"' >> Cargo.toml
echo 'midir = "*"' >> Cargo.toml
cargo run --release
```

Which outputs:

```
error: multiple packages link to native library `alsa`, but a native library can be linked only once

package `alsa-sys v0.1.2`
    ... which is depended on by `alsa v0.2.2`
    ... which is depended on by `midir v0.6.2`
    ... which is depended on by `test-midir-cpal v0.1.0 (/home/docler/tmp/test-midir-cpal)`
links to native library `alsa`

package `alsa-sys v0.3.0`
    ... which is depended on by `alsa v0.4.2`
    ... which is depended on by `cpal v0.12.1`
    ... which is depended on by `test-midir-cpal v0.1.0 (/home/docler/tmp/test-midir-cpal)`
also links to native library `alsa`
```

If you want I can open a PR with a fix that updates `alsa` dependency. I tried locally and it works already, I only had to fix some imports

**Comment by Boddlnagg** [comment]
Sure, we should do this, I'll accept a PR :-)

But I'm not sure if this would be a breaking change for downstream users? I.e., can we release midir 0.6.3 with that change or does it need to be 0.7?

**Comment by Psykopear** [comment]
The PR #63 that shybyte opened is the same code I ended up with.
Since the alsa crate and its structs are not reexported, those changes should not affect users, so yes, I think the update can be included in a path release.
