### ISSUE TITLE
Feature request: ability to have asynchronous MIDI in.

### ISSUE THREAD

**Issue by pietervandermeer** [Boddlnagg/midir#76]
First of all I want to congratulate the author with this lib. It seems like Cpal's counterpart for MIDI. OS independent and minimal fuss to set up. A good bunch of examples as well. 

While I acknowledge that per-packet callbacks for MIDI input is useful, a simple asynchronous (non-blocking) call that just returns the latest byte (or latest packet) from the stream would be ideal for me. I also make code that runs on embedded systems that talk MIDI over USART to microcontrollers and such. For such code it's a lot better to take it byte by byte. It also makes it a lot easier to multitask without the necessity for threads (and threads need locks).

It seems like this feature is easy to implement, but I not a lib developer. Thanks in advance for your answer.

**Comment by pietervandermeer** [comment]
2 hours after my question I solved my problem by using a ringbuf (from the ringbuf crate) to pump data from the closure to my main thread. I don't know about the performance, but it's a fine solution to my problem. I suppose this warrants a close to this issue. Unless this causes significant latency.. 

```
let usbmidi_ring = RingBuffer::<u8>::new(1000); 
let (usbmidi_producer, mut usbmidi_consumer) = usbmidi_ring.split();
// _conn_in needs to be a named parameter, because it needs to be kept alive until the end of the scope
let _conn_in = midi_in.connect(in_port, "midir-read-input", move |_, message, usbmidi_producer| 
{
    for b in message
    {
        usbmidi_producer.push(*b).unwrap();
    }
}, usbmidi_producer).unwrap();
```

The other side then reads from the consumer side of the ringbuffer:
```
let mut usb_data = vec![];
if !usbmidi_consumer.is_empty()
{
    usbmidi_consumer.write_into(&mut usb_data, None).unwrap();
}
```

**Comment by Boddlnagg** [comment]
I think you solved that yourself correctly 👍
