### ISSUE TITLE
How to run WebMIDI example?

### ISSUE THREAD

**Issue by anchpop** [Boddlnagg/midir#83]
I'm trying to figure out how to run the WASM example. Just entering `midir\examples\browser` and running `cargo run` doesn't work, failing with `error: a bin target must be available for cargo run`. And `cargo run --example browser` from the root of the project fails with `error: no example target named browser`.

Additionally, an example of how to play notes in the browser (not just receive them) would be interesting.

**Comment by Boddlnagg** [comment]
In the original PR (https://github.com/Boddlnagg/midir/pull/47) it's explained how to test this (using `wasm-pack`).

In general, receiving input is harder than sending notes, so the latter should be pretty straightforward once you have a working connection to your device.Have a look at the `send` function in `MidiOutputConnection` (https://docs.rs/midir/0.7.0/midir/struct.MidiOutputConnection.html#method.send). You can also have a look at the [`test_play`](https://github.com/Boddlnagg/midir/blob/master/examples/test_play.rs) example, which demonstrates how to play a short melody. That example is not specific for WASM, but when the connection to the device is established, it should work the same way in the browser.

**Comment by anchpop** [comment]
Appreciate it, thank you!
