### ISSUE TITLE
Missing timestamp breaks IAC driver send into Ableton Live

### ISSUE THREAD

**Issue by yamadapc** [Boddlnagg/midir#94]
Hey 👋 , this is somewhat related to #45.

I've found that when sending MIDI into Ableton Live through IAC Driver on macOS, messages were not picked-up, despite the MIDI indicator flashing.

After investigation, I could fix the issue by changing the timestamp of the `PacketBuffer` instances.

```
// midir/src/backend/coremidi/mod.rs
// MidiOutputConnection::send

let packets = PacketBuffer::new(0, message); // <- this apparently confuses Live

// and then:
let host_time = unsafe { external::AudioGetCurrentHostTime() };
let packets = PacketBuffer::new(host_time, message); // <- this works
```

I've found posts on the internet of others hitting this issue. For example: https://forum.ableton.com/viewtopic.php?t=181224

I understand this is a problem specific to Ableton, but it'd be nice to be able to send MIDI onto it using `midir`.

The patch above seems to fix the issue, though there might be a requirement to further offset the 'current host time' by a certain arbitrary small delta. Using `mach2::mach_time::mach_absolute_time()` instead of `AudioGetCurrentHostTime()` also fixes the issue.

All the best; I can raise a PR if you think this change makes sense.

**Comment by yamadapc** [comment]
Diff: https://github.com/yamadapc/midir/pull/new/issue/fix-sending-midi-via-iac

**Comment by Boddlnagg** [comment]
Thank you for looking into this issue and preparing a PR (and sorry that it took me so long to respond)! 
Unfortunately I lack any in-depth knowledge about how this works on macOS, so I'm a bit lost reviewing this PR.
In principle the change looks simple enough and I'm inclined to merge it. However:
1) Is there any possibility of a regression introduced by this change in any other functionality?
2) What makes you think that a further offset would be required?

**Comment by yamadapc** [comment]
> Is there any possibility of a regression introduced by this change in any other functionality?

Hey, I don't there should be a regression. I haven't tested how the MIDI timestamp was interacting with external MIDI hardware.

https://developer.apple.com/documentation/coremidi/midipacket/1495113-timestamp?language=objc

From the documentation `0` should mean to play now, whereas the timestamp would indicate a time. A past timestamp would hopefully still be handled. I suppose this will depend on the software handling the message.

> What makes you think that a further offset would be required?

I've tested that on Ableton Live, using IAC driver to pass MIDI messages between a rust program and ableton, a non-0 timestamp is required. 

The least risky solution for the library would be to provide an option so the consumer can give a timestamp to the events.

This does fix the issue of sending messages to Live though.

**Comment by yamadapc** [comment]
Hey @Boddlnagg, I’m wondering if we could get this change in, either under a feature-flag or via an optional parameter (which I imagine would be something around #45)

**Comment by Boddlnagg** [comment]
Sorry that you didn't hear from me for so long.

I think I'll add a feature flag for this with 0.8.0. We already have a feature flag for a timestamp-related thing with the ALSA backend (`avoid_timestamping`), so this doesn't make things worse. And I want to get 0.8.0 out the door, so I don't want to make API changes.

We can reconsider with 0.9.0 to add an optional timestamp parameter to the API (reachable through some non-portable trait, because as explained in #45 Windows doesn't offer a timestamped API).

**Comment by yamadapc** [comment]
No worries.

Thank you! It looks like that will do it.
