### ISSUE TITLE
How to expose input port to other apps?

### ISSUE THREAD

**Issue by Cactice** [Boddlnagg/midir#96]
With a very simple [fork](https://github.com/Cactice/midir) I was able to get this running on iOS but it seems I cannot select my app as a midi output target from another app.  All I can select from is 'Network Session 1, Sunvox, SP Pro' none of which is my app.
I tried having my app listen to Network Session 1 and output there from sunvox(a sequencer app) to my app but that did not work.

I'm guessing [MIDIInputPortCreateWithProtocol](https://developer.apple.com/documentation/coremidi/3566488-midiinputportcreatewithprotocol) is the api we're supposed to use to expose but I'm not sure how to do it through midir?

![7DDE716C-8D87-44B0-8838-AD500792C5B0](https://user-images.githubusercontent.com/14835424/150154642-9906143f-6afa-4dad-8a28-fb53d648f8bf.png)

**Comment by Boddlnagg** [comment]
Because midir is relying on the [coremidi](https://github.com/chris-zen/coremidi) crate for Apple platforms, I think this should rather be asked in that repository. As long as they don't offer an API that works on iOS, I don't really work around that by calling low-level platform APIs directly ...

**Comment by Cactice** [comment]
I see.
I wasn't sure if this was an iOS specific feature or general midi feature, and it seems to be the former in which case I understand why it wouldn't belong to this repo. 

Thank you. I will close this issue.
